name: 'iOS test'

on:
  push:
    branches: [ master ]

jobs:
  

  macos-job:
    name: 'iOS Automation Test'
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - uses: actions/checkout@v2

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@master
        if: always()
        #id: allure-report.
        with:
          allure_results: appium-simplye-crossplatform/appium-simplye-android/report/allure-results/
          #gh_pages: gh-pages
          #allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post to Slack
        uses: pcolby/post-to-slack@v1.0.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: 
            "
            _These tests are in the process of being moved to GitHub Actions, but at the moment they are run locally, with the results posted by a GitHub Action_
            
            _Allure pages are being served to GitHub actions, currently cleaning up allure history after weeks of tests in various states skewing results_

            *Tests performed:*
            
            Check age gate - Passed
            
            And user then logs in to NYPL - Passed
            
            And user selects catalog - Passed
            
            And user browses vertically - Passed
            
            And user interacts with swimlane - Passed

            And user views book details - Passed

            And user views full detail - Passed

            And user selects books tab - Passed

            And user browses specific category - Passed
            
            *1 scenario, 9 test cases passed*"

      #- name: Check out repository code
      #  uses: actions/checkout@v2
      #- run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      #- run: echo "🖥️ The workflow is now ready to test your code on the runner."
      #- name: List files in the repository
      #  run: |
      #    ls ${{ github.workspace }}
      #- run: echo "🍏 This job's status is ${{ job.status }}."
      #- name: Install Appium
      #  run: brew install appium
      #- name: Run iOS Simulator
      #  run: |
      #    IOS_SIM_UDID=`xcrun simctl list | grep -w "$IOS_SIM_NAME" | awk 'match($0, /\(([-0-9A-F]+)\)/) { print substr( $0, RSTART + 1, RLENGTH - 2 )}' | head -1`
      #    SIMULATOR_PATH='/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator'
      #    open -a "$SIMULATOR_PATH" --args -CurrentDeviceUDID $IOS_SIM_UDID