name: 'iOS test'

on:
  push:
    branches: [ master ]

jobs:
  macos-job:
    name: 'iOS Automation Test'
    runs-on: macos-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Post to Slack
        uses: pcolby/post-to-slack@v1.0.1
        with:
          url: ${{ secrets.SLACK_WEBHOOK_URL }}
          text: >-
            *FORMATTING TEST*
            \n _These tests are in the process of being moved to GitHub Actions, but at the moment they are run locally, with the results posted by a GitHub Action_
            \n *Tests performed:*
            \n Check age gate - Passed
            \n And user then logs in to NYPL - Passed
            \n And user selects catalog - Passed
            \n And user browses vertically - Passed
            \n And user interacts with swimlane - Passed
            \n And user views book details - Passed
            \n And user views full detail - Passed
            \n And user selects books tab - Passed
            \n And user browses specific category - Passed
            \n *1 scenario, 9 test cases passed*

      #- name: Check out repository code
      #  uses: actions/checkout@v2
      #- run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      #- run: echo "🖥️ The workflow is now ready to test your code on the runner."
      #- name: List files in the repository
      #  run: |
      #    ls ${{ github.workspace }}
      #- run: echo "🍏 This job's status is ${{ job.status }}."
      #- name: Install Appium
      #  run: brew install appium
      #- name: Run iOS Simulator
      #  run: |
      #    IOS_SIM_UDID=`xcrun simctl list | grep -w "$IOS_SIM_NAME" | awk 'match($0, /\(([-0-9A-F]+)\)/) { print substr( $0, RSTART + 1, RLENGTH - 2 )}' | head -1`
      #    SIMULATOR_PATH='/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator'
      #    open -a "$SIMULATOR_PATH" --args -CurrentDeviceUDID $IOS_SIM_UDID